language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
install:
  - python setup.py develop
  - pip install -r requirements.txt
  - pip install coveralls
script:
    coverage run --source=thefuck,tests -m py.test -v
after_success:
    coveralls
